<?php
namespace app\components;


use app\models\Cities;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\web\NotFoundHttpException;

class AppController extends Controller
{
    public $selectedCity;
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    public function beforeAction($action)
    {
        $this->selectedCity = \Yii::$app->request->get('city') ? : '';
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}